name: dart_server
description: Servidor Dart (HTTP + Socket.IO) con SQLite
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  socket_io: ^1.0.1     # 👈 baja de ^1.0.2 a ^1.0.1
  sqlite3: ^2.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
