services:
  - type: web
    name: dart-socket-server
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: "/"         # o "/socket.io/" si no sirves "/"
    startCommand: /app/server    # 👈 esto evita que Render use uno incorrecto
